# Generated by Django 5.0 on 2024-04-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphoto',
            name='image',
            field=models.ImageField(upload_to='user_images/%Y/%m/%d'),
        ),
    ]
