# Generated by Django 5.0 on 2024-04-02 14:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_alter_ad_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b5ed9b42-f916-4045-a0fa-165c8755dd33'), editable=False, primary_key=True, serialize=False),
        ),
    ]
