# Generated by Django 5.0 on 2024-04-02 15:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_alter_ad_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('859ab333-3894-4683-9ea3-8daff6bb7bdb'), editable=False, primary_key=True, serialize=False),
        ),
    ]
