# Generated by Django 5.0 on 2024-04-09 12:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_alter_ad_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('12e138e2-0328-4444-bb06-fadeca308e1d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
