# Generated by Django 5.0 on 2024-04-09 12:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0010_alter_ad_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a00f7567-3710-47b0-b7ac-01b3eeabe844'), editable=False, primary_key=True, serialize=False),
        ),
    ]
