# Generated by Django 5.0 on 2024-04-11 15:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0011_alter_ad_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('1262b094-5996-4748-82b4-78c4d312a1fc'), editable=False, primary_key=True, serialize=False),
        ),
    ]
