# Generated by Django 5.0 on 2024-04-11 15:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0012_alter_ad_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('cc1fcdac-637f-479f-aa1f-63295a2e2351'), editable=False, primary_key=True, serialize=False),
        ),
    ]
