# Generated by Django 5.0.4 on 2024-05-02 15:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0015_alter_ad_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a802670d-9349-48c2-8d51-ef39772f2559'), editable=False, primary_key=True, serialize=False),
        ),
    ]
