# Generated by Django 5.0.4 on 2024-05-02 17:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0016_alter_ad_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b92f6a85-6293-4104-8029-b2e1ede50f47'), editable=False, primary_key=True, serialize=False),
        ),
    ]
