# Generated by Django 5.0 on 2024-04-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_app', '0002_book_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='drf_app.author'),
        ),
    ]
